export const state: any = {
  sockets: [],
  players: {},
  playerNames: {},
  trajectories: {},
  trajectoriesEnabled: false,
  trajectoryCanvas: null,
  trajectoryRaf: null,
  localUid: null,
  activeSocket: null,
  serverTimeOffset: 0,
  lastPingTime: 0,
  requestedUserList: false,
  lastSocketOpenedAt: 0,
  lastJoinRecoveryAt: 0,
  seenPlayableStateSinceSocketOpen: false,
  lastKnownRoundHole: null,
  lastKnownRoundState: null,
  powerupMapping: {},
  playerEffectIds: {},
  stealEffectId: null,
  spawnBumperEffectId: null,
  putBumperArmed: false,
  lastKnownLocalState: null,
  group: null,
  uiReady: false,
  systemHookInstalled: false,
  powerupQueue: [],
  powerupRefillTimer: null,
  spawnedBumpers: [],
  deletedPlaceableKeys: new Set(),
  removeFatassesEnabled: false,
  removeFatassesOriginalScales: new Map(),
  welcomeShown: false,
  openModuleCategories: new Set(["Core", "Teleport", "Powerups", "Players", "World", "Visuals"]),
};

export const log = console.log.bind(console);
